// Auto-generated image map - Do not edit manually
// Generated at: 2025-12-17T09:03:36.587Z

export const imageMap = {
  album_1: '/images/album_1.jpeg',
  album_2: '/images/album_2.jpeg',
  anh_thu_1: '/images/anh-thu-1.webp',
  anh_thu_2: '/images/anh-thu-2.webp',
  anh_thu_3: '/images/anh-thu-3.webp',
  anh_thu_4: '/images/anh-thu-4.webp',
  bg1: '/images/bg1.jpeg',
  bg10: '/images/bg10.webp',
  bg11: '/images/bg11.webp',
  bg2: '/images/bg2.jpeg',
  bg3: '/images/bg3.jpeg',
  bg4: '/images/bg4.jpeg',
  bg5: '/images/bg5.jpeg',
  bg6: '/images/bg6.jpeg',
  bg7: '/images/bg7.jpeg',
  bg8: '/images/bg8.jpeg',
  bg9: '/images/bg9.jpeg',
  bride: '/images/bride.jpeg',
  carousel_1: '/images/carousel_1.jpeg',
  carousel_10: '/images/carousel_10.jpeg',
  carousel_11: '/images/carousel_11.jpeg',
  carousel_12: '/images/carousel_12.jpeg',
  carousel_13: '/images/carousel_13.jpeg',
  carousel_14: '/images/carousel_14.jpeg',
  carousel_15: '/images/carousel_15.jpeg',
  carousel_2: '/images/carousel_2.jpeg',
  carousel_3: '/images/carousel_3.jpeg',
  carousel_4: '/images/carousel_4.jpeg',
  carousel_5: '/images/carousel_5.jpeg',
  carousel_6: '/images/carousel_6.jpeg',
  carousel_7: '/images/carousel_7.jpeg',
  carousel_8: '/images/carousel_8.jpeg',
  carousel_9: '/images/carousel_9.jpeg',
  gif_nhac_be_nau_20250718143617_k_wa3: '/images/gif-nhac-be-nau-20250718143617-k_wa3.gif',
  groom: '/images/groom.jpeg',
  header1: '/images/header1.jpeg',
  header2: '/images/header2.jpeg',
  imageFrame_1: '/images/imageFrame_1.jpeg',
  imageFrame_2: '/images/imageFrame_2.jpeg',
  imageFrame_3: '/images/imageFrame_3.jpeg',
  imageFrame_4: '/images/imageFrame_4.jpeg',
  imageFrame_5: '/images/imageFrame_5.jpeg',
  imageFrame_6: '/images/imageFrame_6.jpeg',
  imageFrame_7: '/images/imageFrame_7.jpeg',
  imageFrame_8: '/images/imageFrame_8.jpeg',
  imageFrame_9: '/images/imageFrame_9.jpeg',
  letter_1: '/images/letter-1.jpeg',
  letter_2: '/images/letter-2.jpeg',
  seperator: '/images/seperator.jpeg',
  untitled_1_20250409032644_v_4bn: '/images/untitled-1-20250409032644-v_4bn.webp',
  untitled_dfww_20250420125807_7viyy: '/images/untitled-dfww-20250420125807-7viyy.webp',
  videoFrame: '/images/videoFrame.webp'
} as const;

export type ImageKey = keyof typeof imageMap;
